version: '3'
services:
  ski:
    image: amine283/spring_app:v1
    restart: on-failure
    ports:
      - '8089:8089'
    depends_on:
      - mysql
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: amine
      MYSQL_DATABASE: stationSki
      MYSQL_USER: amine
      MYSQL_PASSWORD: amine
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  .m2:
