version: "3"
services:
  springboot-app:
    image: wejden11/imagepost:latest
    restart: always
    build : .
    ports:
      - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stationski
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: wejdentvd1103
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - /home/User/DESKTOP/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: stationski
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wejdentvd1103
  angular-app:
    image: wejden11/imagefront:latest
    restart: always
    ports:
      - 4200:80


