version: "4"
services:
  springboot-app:

    image: wissemelarbi/Ski-master:1.0.0
    restart: always
    build: .
    ports:
      - 8000-8999:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/User/DESKTOP/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
