version: "4"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/vagrant/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sami2
      MYSQL_PASSWORD: beep2

  ski-app:
    image: benchaabanesami/gestion-station-ski:1.0.0
    restart: always
    build: .
    ports:
      - "8089:8089"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: sami2
      MYSQL_PASSWORD: beep2
      MYSQL_PORT: 3306
