version: "4"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - /home/vagrant/mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sami
      MYSQL_PASSWORD: beep

  ski-app:
    image: benchaabanesami/gestion-station-ski:1.0.0
    restart: always
    build: .
    ports:
      - 8000-8999:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: sami
      MYSQL_PASSWORD: beep
      MYSQL_PORT: 3306
