version: '3.8'
services:
  postgressql:
    image: postgres:latest
    container_name: postgressql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: stationski
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  stationski-container:
    build:
      context: .  
    container_name: stationski-container
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stationski
    depends_on:
      - postgressql
    networks:
      - app-network

volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge
