version: '3'
services:
  ski:
    image: amine-skier-spring_app:latest
    restart: on-failure
    ports:
      - '8088:8089'
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3309/stationSki?createDatabaseIfNotExist=true&userSSL=false&max_allowed_packet=15728640
      - SPRING_DATASOURCE_USERNAME=amine
      - SPRING_DATASOURCE_PASSWORD=amine
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    networks:
      - mynetwork
    volumes:
      - .m2:/root/.m2

  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: amine
      MYSQL_DATABASE: stationSki
      MYSQL_USER: amine
      MYSQL_PASSWORD: amine
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  .m2:
