version: '3'
services:
 mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: amine
      MYSQL_DATABASE: stationSki
      MYSQL_USER: amine
      MYSQL_PASSWORD: amine
    network_mode: bridge
    volumes:
      - mysql-data:/var/lib/mysql   
  ski:
    image: amine-skier-spring_app:latest
    restart: on-failure
    ports:
      - '8088:8088'
    depends_on:
      - mysql
    network_mode: bridge
    volumes:
      - .m2:/root/.m2
volumes:
  mysql-data:
  .m2:
