global:
  scrape_interval: 15s

  - job_name: spring
    metrics_path: /api/actuator/prometheus
    static_configs:
      - targets: ['192.168.8.104:8089']


  - job_name: 'Jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.8.104:8080']
      
 
